---
services:
  giphymcp:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.giphymcp
    container_name: giphymcp
    restart: unless-stopped
    environment:
    #  - GIPHY_API_KEY=${GIPHY_API_KEY} # Ensure this is set in your .env file or environment
      - LOG_LEVEL=INFO # Or DEBUG for more verbose logging
      - GIPHY_MCP_SERVER_PORT=6700
    networks:
      - intranet

  ytmcp:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ytmcp
    container_name: ytmcp
    restart: unless-stopped
    environment:
    #   - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - LOG_LEVEL=INFO
      - YOUTUBE_MCP_SERVER_PORT=6700
    networks:
      - intranet

  usersmcp:
    build:
       context: .
       dockerfile: dockerfiles/Dockerfile.usersmcp
    container_name: usersmcp
    restart: unless-stopped
    environment:
      - USER_API_BASE_URL=http://usercontext_api:9000/api/v1
      - LOG_LEVEL=INFO
    networks:
      - intranet

  wamcp:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.wamcp
    container_name: wamcp
    restart: unless-stopped
    environment:
      #- WOLFRAMALPHA_APP_ID=${WOLFRAMALPHA_APP_ID} # Pass the App ID from your .env file or host environment
      - LOG_LEVEL=INFO
      - WOLFRAMALPHA_MCP_SERVER_PORT=6700
    networks:
      - intranet

  pistonmcp:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.pmcp
    container_name: pistonmcp
    restart: unless-stopped
    environment:
      - PISTON_MCP_PORT=6700
      - PISTON_API_BASE_URL=https://emkc.org/api/v2/piston
      - LOG_LEVEL=INFO
    networks:
      - intranet

  cvemcp:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.cvemcp
    container_name: cvemcp
    restart: unless-stopped
    environment:
      - CVE_MCP_PORT=6700
      # - NVD_API_KEY=${NVD_API_KEY} # Optional: NVD API key for higher rate limits
      - LOG_LEVEL=INFO
    networks:
      - intranet

  tenormcp:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.tenormcp
    container_name: tenormcp
    restart: unless-stopped
    environment:
      - TENOR_MCP_SERVER_PORT=6700
      # - TENOR_API_KEY=${TENOR_API_KEY} # Ensure this is set in your .env file or environment
      - TENOR_CONTENT_FILTER=medium
      - TENOR_LOCALE=en_US
      - LOG_LEVEL=INFO
    networks:
      - intranet
      
networks:
  intranet:
    external: true