---
services:
  # MCP Servers (all on port 6700 internally)
  giphymcp:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.giphymcp
    container_name: giphymcp
    restart: unless-stopped
    environment:
      - LOG_LEVEL=INFO
      - GIPHY_MCP_SERVER_PORT=6700
    networks:
      - intranet

  ytmcp:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ytmcp
    container_name: ytmcp
    restart: unless-stopped
    environment:
      - LOG_LEVEL=INFO
      - YOUTUBE_MCP_SERVER_PORT=6700
    networks:
      - intranet

  usersmcp:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.usersmcp
    container_name: usersmcp
    restart: unless-stopped
    environment:
      - USER_API_BASE_URL=http://usercontext_api:9000/api/v1
      - USER_MCP_PORT=6700
      - LOG_LEVEL=INFO
    networks:
      - intranet

  wamcp:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.wamcp
    container_name: wamcp
    restart: unless-stopped
    environment:
      - LOG_LEVEL=INFO
      - WOLFRAMALPHA_MCP_SERVER_PORT=6700
    networks:
      - intranet

  pistonmcp:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.pmcp
    container_name: pistonmcp
    restart: unless-stopped
    environment:
      - PISTON_MCP_PORT=6700
      - PISTON_API_BASE_URL=https://emkc.org/api/v2/piston
      - LOG_LEVEL=INFO
    networks:
      - intranet

  cvemcp:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.cvemcp
    container_name: cvemcp
    restart: unless-stopped
    environment:
      - CVE_MCP_PORT=6700
      - LOG_LEVEL=INFO
    networks:
      - intranet

  tenormcp:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.tenormcp
    container_name: tenormcp
    restart: unless-stopped
    environment:
      - TENOR_MCP_SERVER_PORT=6700
      - TENOR_CONTENT_FILTER=medium
      - TENOR_LOCALE=en_US
      - LOG_LEVEL=INFO
    networks:
      - intranet

  # MCPO Proxies (all on port 7700 internally, no external ports)
  giphymcpo:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.giphymcpo
    container_name: giphymcpo
    restart: unless-stopped
    networks:
      - intranet
    depends_on:
      - giphymcp

  ytmcpo:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ytmcpo
    container_name: ytmcpo
    restart: unless-stopped
    networks:
      - intranet
    depends_on:
      - ytmcp

  usersmcpo:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.usersmcpo
    container_name: usersmcpo
    restart: unless-stopped
    networks:
      - intranet
    depends_on:
      - usersmcp

  wamcpo:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.wamcpo
    container_name: wamcpo
    restart: unless-stopped
    networks:
      - intranet
    depends_on:
      - wamcp

  pistonmcpo:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.pmcpo
    container_name: pistonmcpo
    restart: unless-stopped
    networks:
      - intranet
    depends_on:
      - pistonmcp

  cvemcpo:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.cvemcpo
    container_name: cvemcpo
    restart: unless-stopped
    networks:
      - intranet
    depends_on:
      - cvemcp

  tenormcpo:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.tenormcpo
    container_name: tenormcpo
    restart: unless-stopped
    networks:
      - intranet
    depends_on:
      - tenormcp

  # MCP Client (for testing)
  mcpclient:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.client
    container_name: mcpclient
    restart: "no"
    networks:
      - intranet
    depends_on:
      - giphymcp
      - ytmcp
      - usersmcp
      - wamcp
      - pistonmcp
      - cvemcp
      - tenormcp

networks:
  intranet:
    external: true